### ISSUE TITLE
fix image state lost after scrolling

### ISSUE THREAD

**Issue by eroux** [buda-base/scam#10]
There are cases where the following happens:
- modify bounding boxes by hand
- scroll far away
- come back to the image
- the modifications made by hand are lost

**Comment by berger-n** [comment]
fixed: https://scamqc.bdrc.io/?folder=Bruno%2FReruk%2F

![simplescreenrecorder-2024-01-04_14 23 57 mkv](https://github.com/buda-base/scam/assets/33383857/c7f5565f-ab37-4d75-82c6-d38be096f27f)

**Comment by eroux** [comment]
thanks!
