### ISSUE TITLE
compute all images in a run

### ISSUE THREAD

**Issue by eroux** [buda-base/scam#11]
instead of implementing a relatively long `run_scam` on all the images, let's implement the following instead: when computation is requested on a batch of images, the following happens:
- a computation job is created, that has a progress bar and a cancel button
- no job can be started without cancelling the previous job
- a user cannot save or upload without cancelling the job
- images that need to be computed by the job but are not yet computed display an overlay spinner

This is to avoid the case where a user reviews 80% of the images and believes that the rest is computed (since computation is really fast)

**Comment by berger-n** [comment]
not deployed yet (as it needs more testing/debugging, especially when running on a subset) but already on good tracks: 

![simplescreenrecorder-2024-01-09_18 45 02 mkv](https://github.com/buda-base/scam/assets/33383857/1bb0936e-5ba7-4ebb-92aa-23bee64a36b9)

**Comment by berger-n** [comment]
just deployed: https://scamqc.bdrc.io/?folder=Sarah-Library%2FW2KG210280%2Fimages%2FW2KG210280-I3KG366%2F

![simplescreenrecorder-2024-01-10_17 40 05 mkv](https://github.com/buda-base/scam/assets/33383857/30176a69-afc1-43e5-8ea9-e1cb781171c3)

note that it won't autostart anymore when page is loaded (but I can add that feature back if needed) so there's a state with "no data" / "! in a circle" icon

also, the calls to run_scam_file are parallelized (six at a times) 
maybe we could set this number as a parameter? 
it used to be very high when based on scroll 
(though it seems to prevent images from loading when it's too high)

**Comment by eroux** [comment]
great, thanks a lot!
