### ISSUE TITLE
add "check all previous images" button

### ISSUE THREAD

**Issue by eroux** [buda-base/scam#12]
on an image it should be possible to click somewhere and check all previous images (including this one)

**Comment by berger-n** [comment]
done (using a menu when the check/uncheck button is clicked): https://scamqc.bdrc.io/?folder=Sarah-Library%2FW2KG210280%2Fimages%2FW2KG210280-I3KG366%2F

![simplescreenrecorder-2024-01-04_17 48 13 mkv](https://github.com/buda-base/scam/assets/33383857/b19723d1-0fa5-4a6e-bf1d-83128c7f9a18)

the same feature could be useful for hiding images as well, couldn't it?

**Comment by eroux** [comment]
this looks perfect, thanks a lot!
