### ISSUE TITLE
check all images modified by hand

### ISSUE THREAD

**Issue by eroux** [buda-base/scam#13]
I'm not sure it should be the default but in most cases when a user modifies an image by hand we could consider it checked... I think this could be the default, then the user can uncheck it

**Comment by berger-n** [comment]
done: https://scamqc.bdrc.io/?folder=Sarah-Library%2FW2KG210280%2Fimages%2FW2KG210280-I3KG366%2F

![simplescreenrecorder-2024-01-05_11 37 00 mkv](https://github.com/buda-base/scam/assets/33383857/d53b6b98-69b7-4b0e-937b-d894f8c59810)

**Comment by eroux** [comment]
perfect, thanks!

**Comment by eroux** [comment]
I thought this would be a good idea but turns out that with the users we expect it's a very bad idea, @berger-n can you undo it please? (or put it behind an option in the code? no need to have the option in the ui)

**Comment by berger-n** [comment]
just commented out the few lines involved (easy to revert if needed one day): https://scamqc.bdrc.io/?folder=Sarah-Library%2FW2KG210280%2Fimages%2FW2KG210280-I3KG366%2F

![simplescreenrecorder-2024-02-02_11 39 16 mkv](https://github.com/buda-base/scam/assets/33383857/c1f9c774-c5db-4f7c-9ace-13f7c76f0efe)

**Comment by eroux** [comment]
perfect, thanks!
