### ISSUE TITLE
improve scrolling experience

### ISSUE THREAD

**Issue by eroux** [buda-base/scam#14]
when hitting the scrollbar, the scrolling could align the images in a consistent way on the screen so that when hitting the space bar multiple times the images are always on the same place on the screen, making it easier to review

**Comment by berger-n** [comment]
now when hitting space (resp. shift+space) the scrolling jumps to the top of the next (resp. previous) images that are only partially visible: https://scamqc.bdrc.io/?folder=X_Basgo_Complete%2F10+mDo%2FmDo+04+Nga+%28aus+Phal+chen%29%2F

![simplescreenrecorder-2024-01-05_18 27 57 mkv](https://github.com/buda-base/scam/assets/33383857/de9d491b-b20a-4794-bcc6-f67a086cdf63)

**Comment by eroux** [comment]
this is really a great improvement, thanks!
