### ISSUE TITLE
copy / pasting box

### ISSUE THREAD

**Issue by eroux** [buda-base/scam#15]
in cases where the pages are a bit repetitive but the detection doesn't work that well (like on https://scamqc.bdrc.io/?folder=LTWA2023withacc%2F002841%2F ), it would be super useful to have a way to copy / paste a box

**Comment by berger-n** [comment]
done using CTRL+C/V/X: https://scamqc.bdrc.io/?folder=LTWA2023withacc%2F002841%2F

![simplescreenrecorder-2024-01-11_18 42 29 mkv](https://github.com/buda-base/scam/assets/33383857/ea99f689-ae64-4f88-8d42-00aef1e92cc5)

**Comment by eroux** [comment]
wow, this is very cool, thanks a lot!!

**Comment by berger-n** [comment]
thinking of a "duplicate annotation" button right here so we don't have to rely on keyboard shortcuts 

![image](https://github.com/buda-base/scam/assets/33383857/dc75564a-969d-4ded-aa5c-0a68ee4ed72e)
