### ISSUE TITLE
faster custom configuration

### ISSUE THREAD

**Issue by eroux** [buda-base/scam#16]
in the custom config window we should have a button "import from selected annotation" that would basically fill the 4 input fields at once, by using annotation value + / - 10% (or maybe 15% to be sure)

**Comment by berger-n** [comment]
done: https://scamqc.bdrc.io/?folder=LTWA2023withacc%2F002841%2F

![simplescreenrecorder-2024-01-11_17 15 46 mkv](https://github.com/buda-base/scam/assets/33383857/b12139a8-2147-4705-8906-f9ed05982b9c)

**Comment by eroux** [comment]
this works perfectly, thanks!
