### ISSUE TITLE
better label for configuration mode

### ISSUE THREAD

**Issue by eroux** [buda-base/scam#17]
we should have "configuration" instead of "Pages orientation" at the top of the configuration window. Also the "Direction" configuration should probably be named "annotation layout" and the choices could be "horizontal (left to right)" and "vertical (top to bottom)", that field can have its own line in the window

**Comment by berger-n** [comment]
done: https://scamqc.bdrc.io/?folder=LTWA2023withacc%2F002841%2F

![simplescreenrecorder-2024-01-11_15 15 43 mkv](https://github.com/buda-base/scam/assets/33383857/3b4d9f1e-eaf8-4c12-81b9-bd7c4e0ec202)

**Comment by eroux** [comment]
perfect, thanks!
