### ISSUE TITLE
custom parameters "leaking" into presets

### ISSUE THREAD

**Issue by eroux** [buda-base/scam#19]
I'm not entirely sure it's that but I've set up the number of expected pages to 4 in the custom properties, but if I visit https://scamqc.bdrc.io/?folder=Sarah-Library%2FW2KG210280%2Fimages%2FW2KG210280-I3KG366%2F and use the preset vertical settings, I'm getting warnings on all images even if they have 2 pages detected (which should be the default)

**Comment by berger-n** [comment]
should be fixed now: https://scamqc.bdrc.io/?folder=Sarah-Library%2FW2KG210280%2Fimages%2FW2KG210280-I3KG366%2F

![simplescreenrecorder-2024-01-11_14 43 46 mkv](https://github.com/buda-base/scam/assets/33383857/ea2865b9-cae9-4732-b44d-49437503c799)

**Comment by eroux** [comment]
looks good, thanks!
