### ISSUE TITLE
"run scam" button

### ISSUE THREAD

**Issue by eroux** [buda-base/scam#20]
instead of the small cog button in the bottom left corner, there should be a big red "run SCAM" button in red at the top or bottom

**Comment by berger-n** [comment]
done: https://scamqc.bdrc.io/?folder=LTWA2023withacc%2F000950%2F

![simplescreenrecorder-2024-01-12_11 29 11 mkv](https://github.com/buda-base/scam/assets/33383857/55ba2b2e-7c31-4ecb-b9cc-82a67809527d)

**Comment by eroux** [comment]
perfect, thanks!
