### ISSUE TITLE
only run on images with warnings checkbox in run scam window

### ISSUE THREAD

**Issue by eroux** [buda-base/scam#21]
in addition to "only run on selected images", another checkbox should be "only run on images with warnings" in the run scam window

**Comment by berger-n** [comment]
done: https://scamqc.bdrc.io/?folder=LTWA2023withacc%2F002841%2F

![simplescreenrecorder-2024-01-12_14 16 07 mkv](https://github.com/buda-base/scam/assets/33383857/b26df315-ef6f-48d9-938d-7f2eafe025a4)

**Comment by eroux** [comment]
perfect, thanks!
