### ISSUE TITLE
bug when running scam

### ISSUE THREAD

**Issue by eroux** [buda-base/scam#22]
it's not a very big bug and I couldn't reproduce it but here's what happened: I ran scam with some custom params on https://scamqc.bdrc.io/?folder=LTWA2023withacc%2F002841%2F and the last two pages seemed like they had no pages detected (none). But then when I try to create an annotation on one of these images, suddenly all the annotations appear

**Comment by berger-n** [comment]
looks fixed: https://scamqc.bdrc.io/?folder=LTWA2023withacc%2F001701%2F

![simplescreenrecorder-2024-01-12_15 09 27 mkv](https://github.com/buda-base/scam/assets/33383857/dab1e3d3-210f-47fc-81cd-49af40c7cf56)

**Comment by eroux** [comment]
looks fixed, thanks!
