### ISSUE TITLE
update of #13

### ISSUE THREAD

**Issue by eroux** [buda-base/scam#23]
in cases (like https://scamqc.bdrc.io/?folder=LTWA2023withacc%2F002841%2F ) the current workflow doesn't work really well: the user needs to create an annotation, and then use it to create custom params. But then because the user creates the annotation the image becomes checked and the user needs to uncheck it in order to find the other pages. I'm not totally sure how to fix that... can we automatically check the image only if it's a modification of an existing annotation and not in the case of a new annotation?

**Comment by berger-n** [comment]
done: https://scamqc.bdrc.io/?folder=LTWA2023withacc%2F002841%2F

![simplescreenrecorder-2024-01-12_11 46 33 mkv](https://github.com/buda-base/scam/assets/33383857/1c24b3c7-83d4-42bd-8526-f738a92e4367)

**Comment by eroux** [comment]
perfect, thanks!
