### ISSUE TITLE
select images with no warnings

### ISSUE THREAD

**Issue by eroux** [buda-base/scam#24]
in some cases I want to mark all the images with no warnings as checked, it would be useful to have the possibility to do that, next to the "select images with warnings"

**Comment by berger-n** [comment]
done: https://scamqc.bdrc.io/?folder=Bruno%2FReruk%2F

<img width="720" src="https://github.com/buda-base/scam/assets/33383857/8f619de3-bd57-4b94-a994-e6f2b8638ac9"/>

---


also, found this case when only images with warning are shown and then you add an annotation but before you can fine tune it the image has been filtered out, wdyt? [edit: nevermind, found a workaround waiting for the focus to be lost (but seems not to work in every case yet, see capture at the bottom below)]

![simplescreenrecorder-2024-01-15_18 16 00 mkv](https://github.com/buda-base/scam/assets/33383857/43dbff6c-1448-4338-b5dc-7fc4eab86788)
---

![simplescreenrecorder-2024-01-15_18 35 24 mkv](https://github.com/buda-base/scam/assets/33383857/087fc17c-1c07-406a-b8af-099477075118)

**Comment by eroux** [comment]
this is perfect thanks! this corner case is a bit funny... let's ignore it for now
