### ISSUE TITLE
indicate total number of images in the UI

### ISSUE THREAD

**Issue by eroux** [buda-base/scam#26]
Just as an info somewhere, it can be very useful to know the number of images in a volume (just to estimate the size)

**Comment by berger-n** [comment]
done this: https://scamqc.bdrc.io/?folder=Sarah-Library%2FW2KG210280%2Fimages%2FW2KG210280-I3KG366%2F

![image](https://github.com/buda-base/scam/assets/33383857/d9e3be81-30d8-4b82-bea8-38ac429a4c5a)

**Comment by eroux** [comment]
looks perfect, thanks!
