### ISSUE TITLE
second popup unnecessary when saving

### ISSUE THREAD

**Issue by eroux** [buda-base/scam#28]
When the user clicks on upload with the ready to process checked, there's a popup warning that the images are already ready to process, let's remove it in that case

**Comment by berger-n** [comment]
fixed: https://scamqc.bdrc.io/?folder=Sarah-Library%2FW2KG210280%2Fimages%2FW2KG210280-I3KG366%2F

![simplescreenrecorder-2024-01-17_10 56 18 mkv](https://github.com/buda-base/scam/assets/33383857/34e95f18-1779-4d6d-ae51-cd83f9fceec5)

**Comment by eroux** [comment]
perfect, thanks!
