### ISSUE TITLE
QC : mozaic view

### ISSUE THREAD

**Issue by eroux** [buda-base/scam#29]
It would be useful for QC purposes to have a quick glance at the whole volume to check if there are obvious mistakes. Two options:
- [ ] a view of everything in small size, with no space between images (no tile margin)
- [ ] a view of a randomized subset of 10% of the images that the user needs to double check

these could be in the selects in the bottom bar

**Comment by eroux** [comment]
also when we filter only images with a warning in the view, it should have placeholders for the other images, it makes it pretty difficult to navigate when there are a lot of images

**Comment by berger-n** [comment]
almost done with the mozaic view: https://scamqc.bdrc.io/?folder=Bruno%2FReruk%2F
(then there will be a "random" selector to use in combination)

<img src="https://github.com/buda-base/scam/assets/33383857/61028d5e-365c-4f38-a98d-5f2dd7cafbf7" width="720" />


---

BTW you should experience far less "blinking" I think whatever the view mode
(but I need to do the same when images are filtered out or hidden, that is keep the same size whether they are already loaded or not)

**Comment by berger-n** [comment]
\+ couldn't the thumbnails have some "cache" header so that they don't need to be reloaded each time?

**Comment by eroux** [comment]
this is great, thanks a lot!! oh, right, let me add that header

**Comment by eroux** [comment]
thumbnails now should have a header

**Comment by berger-n** [comment]
now the image name is shown in grid mode when filtered out, on hover as well
\+ added the random subset filter: https://scamqc.bdrc.io/?folder=Bruno%2FReruk%2F
BTW the header works, no more reloading! thanks

<img src="https://github.com/buda-base/scam/assets/33383857/e322ee66-18af-47fa-b311-ce0cb97344fa" width="720"/>

**Comment by eroux** [comment]
that looks perfect, thanks! thanks for identifying the header issue too!
