### ISSUE TITLE
heuristics for Sarah Library

### ISSUE THREAD

**Issue by eroux** [buda-base/scam#3]
I've run scam on W1KG15011, it works without error in the most common case but requires a little bit of QC on some of the cover pictures, so overall it seems easily usable. The main issue is that it doesn't seem to cut a part that we probably would usually cut, here's an example:

![20220330153544645_0114](https://github.com/buda-base/archive-ops/assets/60868/f847f5b5-da66-4237-8a47-8a1c3cc2450f)

cropped into

![20220330153544645_0114a](https://github.com/buda-base/archive-ops/assets/60868/ea05bf39-2f1b-43ba-8f11-27df788bdac2)

and

![20220330153544645_0114b](https://github.com/buda-base/archive-ops/assets/60868/f9fd9b74-9a7b-4c53-9949-232f351eef99)

Now, it might be possible to remove the part on the left of the left page, but that will require a little bit of work. I'll try to do that soon, based on the following mask that is found by SAM and could be substracted

![20220330153544645_0114 jpg_003_mask](https://github.com/buda-base/scam/assets/60868/a003e805-abdc-44d0-8f19-965f40d183c0)

**Comment by eroux** [comment]
I managed to find a way to cut the left side on some images but not all (sometimes SAM just doesn't detect the right area). Now, fixing this is not something that I can fully automate (because each volume has different dimensions) but that could be part of some QC tools. Here's an example algorithm that, I think, should fully work automatically:
- for each file ending in `a` (so left page), cut the image `x` pixels from the right
- for each file ending in `b` (right page), cut the image `x` pixels from the left

if we assume that all the pages are of the same pixel size (which should work), then it's just a matter of finding the right value of `x` for each volume and then running things automatically. I'm cropping the 150 volumes from Sarah, they should land on Incoming on Monday.

**Comment by jimk-bdrc** [comment]
That’s a risky approach to assume ‘a’ is left and ‘b’ is right. If you use this extra crop approach, it should be in the step where we’re preparing an access version for humans (say, for BUDA). If we’re preparing a version for OCR, any cropping that is not sensitive to what it is cropping (i.e, isn’t looking at the pixels it’s cropping risks the OCR. 

I wonder if a refined cropping step, in a separate process, after the pages are split, to detect and deskew the text in each page might be a better approach, rather than trying to do both at once.

**Comment by eroux** [comment]
I'm not entirely sure what you're suggesting concretely? We currently only have one set of derived images, that are both for humans and OCR; I don't think that's going to change before we put these 150 volumes online. I also don't think we should have different images for OCR and humans: part of the OCR workflow will be to deskew lines but then "re-skew" when saving character coordinates data, so that we know where characters are in the image.

What I'm discussing here is solely about removing the left border of the left page for cropping, nothing more, I'm just suggesting a quick hack to achieve this quickly. It would admittedly require a bit of QC, but at that stage the whole cropping workflow does.

**Comment by eroux** [comment]
Also, maybe it wasn't clear, I'm not proposing to integrate this little hack in scam, it would be in a subsequent step

**Comment by jimk-bdrc** [comment]
Ah, that's fine to put it in a step later. Concretely, I'm suggesting that we not assume there's only one output. (I know, that's not very concrete)
Although your current work edits images and produces cropped output, we're looking beyond that in the future (partly to avoid download charges for Hi res masters). Just have no idea when that future arrives.

**Comment by eroux** [comment]
done another way
