### ISSUE TITLE
better memory of settings

### ISSUE THREAD

**Issue by eroux** [buda-base/scam#30]
I've used scam on 100 volumes now and the main thing that I think could be improved is remembering previous settings from one volume to the next (maybe through the local storage ?). A typical example is that I usually want custom setting with vertical layout, but every time I change the volume I have to specify custom and then vertical layout. It's not that big a deal but it would make the experience a bit better

**Comment by berger-n** [comment]
should be fixed now: https://scamqc.bdrc.io/?folder=LTWA2023withacc%2FD02335%2F

![simplescreenrecorder-2024-01-22_18 14 54 mkv](https://github.com/buda-base/scam/assets/33383857/aa860c74-6d43-4dc9-9aa3-00b30329e3cf)
