### ISSUE TITLE
annotation tags

### ISSUE THREAD

**Issue by eroux** [buda-base/scam#31]
It will actually be important quite soon to have a way for users to tag annotations, with two important ones:
- color card
- neutral gray area

I'm not sure what the best UI would be for that... but we could start with right click -> "tag as" unless you have a better idea? this is part of #27 . The rest can wait but this will be quite important in the short term

**Comment by eroux** [comment]
an example where the tags will be relevant is https://scamqc.bdrc.io/?folder=NLM1%2FW2KG208160%2Fsources%2FW2KG208160-I2KG208411%2F

**Comment by berger-n** [comment]
this is still work in progress but here's what I have in mind (a "tag" icon in the image menu at the bottom of each image, clickable when an annotation is selected, then the tags will be displayed somewhere around the border of the annotation I think): https://scamqc.bdrc.io/?folder=NLM1%2FW2KG208160%2Fsources%2FW2KG208160-I2KG208411%2F

![simplescreenrecorder-2024-01-19_18 20 54 mkv](https://github.com/buda-base/scam/assets/33383857/cb40feb6-05d1-4286-892c-4233bf6b5bbf)

regarding the data structure to store it (not implemented yet) something like that should work:
```
pages : [
    {
        "minAreaRect": [
            1042.9304846938767,
            421.43996879496234,
            746.1927150607072,
            1081.5918367346958,
            90
        ],
        "warnings": [],
        "tags": [ "color card" ]
    }
]
```

BTW I've also shortened the displayed filenames (`img_path`)
removed the leading path if any and the trailing file extension: 
`RDO_RJE_GRAGS_PA/RDO_RJE_GRAGS_PA_01_0000.CR2` --> `RDO_RJE_GRAGS_PA_01_0000`

**Comment by eroux** [comment]
this is very good, thanks a lot! let's:
- have only "white patch" and "color card"
- use identifiers in the json file (not in the UI), can be `T1` and `T2` for now

**Comment by eroux** [comment]
that looks perfect, thanks a lot!
