### ISSUE TITLE
reformulate "ready to be processed"

### ISSUE THREAD

**Issue by eroux** [buda-base/scam#32]
let's change the popup at the end and have the checkbox read "reviewed complete" and be checked by default

**Comment by berger-n** [comment]
done: https://scamqc.bdrc.io/?folder=Sarah-Library%2FW2KG210280%2Fimages%2FW2KG210280-I3KG366%2F

![simplescreenrecorder-2024-01-22_17 44 12 mkv](https://github.com/buda-base/scam/assets/33383857/8f787991-f0a8-4581-82ae-01305ee37a3c)

**Comment by eroux** [comment]
oops, can you change it to "review complete" (sorry, my mistake), otherwise it's good, thanks!

**Comment by eroux** [comment]
thanks!
