### ISSUE TITLE
add more tags

### ISSUE THREAD

**Issue by eroux** [buda-base/scam#35]
here are a few additional tags that would be helpful:
- detail
- catalog card
- missing page card

**Comment by berger-n** [comment]
done: https://scamqc.bdrc.io/?folder=demo%2FW1KG8718-I1KG8739%2F

![image](https://github.com/buda-base/scam/assets/33383857/d8f98d30-f840-4c82-9bbd-fc7b81a23e9d)

**Comment by eroux** [comment]
perfect, thanks!
