### ISSUE TITLE
hidden images in uploaded data not hidden anymore after reuploading

### ISSUE THREAD

**Issue by berger-n** [buda-base/scam#36]
see https://scamqc.bdrc.io/?folder=Bruno%2FReruk%2F
(sorry for that, not sure when it happened)

**Comment by berger-n** [comment]
not fixed yet, reopening

**Comment by berger-n** [comment]
seems to be fixed now: https://scamqc.bdrc.io/?folder=Sarah-Library%2FW2KG210280%2Fimages%2FW2KG210280-I3KG366%2F

![simplescreenrecorder-2024-01-24_18 20 57 mkv](https://github.com/buda-base/scam/assets/33383857/513c2e5d-0c71-4def-8067-85bdb9f311f4)

**Comment by eroux** [comment]
thanks!
