### ISSUE TITLE
trying to load a draft hangs scamqc ui

### ISSUE THREAD

**Issue by TBRC-Travis** [buda-base/scam#39]
I'm trying to load a draft for W1ER158:  https://scamqc.bdrc.io/?folder=Travis%2FW1ER158%2Farchive%2FW1ER158-I1ER911%2F

When it prompts me with "Draft Found" and asks to load previous edits I hit the YES button and then it just shows a blank screen.

**Comment by berger-n** [comment]
fixed: https://scamqc.bdrc.io/?folder=Travis%2FW1ER158%2Farchive%2FW1ER158-I1ER911%2F

![image](https://github.com/buda-base/scam/assets/33383857/4e2c44cc-756b-4345-9026-d0459e55b0b7)
