### ISSUE TITLE
post-processing: ignore identical bboxes

### ISSUE THREAD

**Issue by eroux** [buda-base/scam#41]
I anticipate that some copy/paste will be made in the initial image instead of another, leaving multiple annotations with the same bbox (pixel coordinates), even though it would be better not to have that, one way to make the problem disappear is to just ignore identical bboxes. I'll do that in the post processing python script, but I wonder if maybe the js could do it in the export too, that would create cleaner json files... what do you think Nicolas?

**Comment by berger-n** [comment]
good idea! now it removes duplicate annotations both in draft and uploaded file: https://scamqc.bdrc.io/?folder=demo%2FW1KG8718-I1KG8739%2F

![simplescreenrecorder-2024-02-08_15 53 13 mkv](https://github.com/buda-base/scam/assets/33383857/1bafee3c-61b1-4150-b82c-18b548ed1a67)

**Comment by eroux** [comment]
done on the server too
