### ISSUE TITLE
icon for the rotation handle

### ISSUE THREAD

**Issue by eroux** [buda-base/scam#42]
I'm not sure the annotator who worked today really understood how to rotate, is it possible to have a more explicit icon on the rotation handle for annotation? currently it's a square like the corners, maybe something round or some arrows?

**Comment by berger-n** [comment]
done: https://scamqc.bdrc.io/?folder=Sarah-Library%2FW2KG210280%2Fimages%2FW2KG210280-I3KG366%2F

![image](https://github.com/buda-base/scam/assets/33383857/d2379e22-7e93-4189-b1b0-410471285912)

**Comment by eroux** [comment]
Great, thanks!
