### ISSUE TITLE
make small annotations easier to see

### ISSUE THREAD

**Issue by eroux** [buda-base/scam#43]
In some cases annotators will add some small noisy / erroneous annotations a bit randomly, they're currently quite difficult to see (which makes QC quite difficult), example:

![wrong52](https://github.com/buda-base/scam/assets/60868/832bca0f-39d6-4bd5-b187-2bb1bddaf90a)

has in fact 5 annotations, not 3, one is a tiny rectangle at the top, another is barely visible and is inside page 2.

Some possible fixes are:
- showing (in small font) the number of annotations on each image (even checked), so that this kind of case is easier to detect (it will also improve things for #41)
- making the colors a bit different maybe?
- have a way to not display the thumbnails and instead just the annotations. I'm on a laggy Internet today so thumbnails don't load very fast, and I realize that not having the thumbnails is sometimes quite helpful, so maybe there could be a button "display annotations only" somewhere in the UI that could be toggled for the whole directory?

**Comment by eroux** [comment]
N.B.: we should also probably add a mechanism to ignore those in the post processing

**Comment by eroux** [comment]
or maybe we can add a warning in the UI (with the same warning UI as usual) for cases where there's a huge difference between the largest and the smallest annotations (like a factor of 100 in area), or when there are duplicate boxes

**Comment by eroux** [comment]
here's the same image without the thumbnails, easier to debug for that case:

![nothumb](https://github.com/buda-base/scam/assets/60868/7f1db053-009d-4455-b271-41ba35c91926)

**Comment by berger-n** [comment]
added *#annotations / expected* as a first step: https://scamqc.bdrc.io/?folder=demo%2FW1KG8718-I1KG8739%2F

![image](https://github.com/buda-base/scam/assets/33383857/e9971c45-87ac-408c-b9a7-1e7f02df6595)

then there could be a warning when more than expected (which could not be bypassed by checking the image? wdyt?)
also yes there could be a different color for annotations "100x" smaller
(not sure where to put the "no thumbnail" option yet but I'll find a way!)

**Comment by eroux** [comment]
this is a great start, thanks a lot!

**Comment by berger-n** [comment]
- small annotations (with area < 100x the largest) get a warning:

![image](https://github.com/buda-base/scam/assets/33383857/07b5becf-31fb-470d-82c7-21885aad9c4a)
---

- warning now stays when image checked but too much annotations:

![image](https://github.com/buda-base/scam/assets/33383857/355c0705-e29c-41d4-aaa0-2d15fd2571f1)

**Comment by eroux** [comment]
this is great, thanks a lot!

**Comment by berger-n** [comment]
fixed keeping small annotation orange when image checked: https://scamqc.bdrc.io/?folder=demo%2FW1KG8718-I1KG8739%2F

![image](https://github.com/buda-base/scam/assets/33383857/eb3bbbe4-61c4-4250-a5c8-5c4df74091a6)
---

added menu entry (in *Filter images*) to toggle thumbnail loading:

![simplescreenrecorder-2024-02-07_14 52 30 mkv](https://github.com/buda-base/scam/assets/33383857/85ecfd09-c9ef-470b-adbe-95307f24e25b)

**Comment by eroux** [comment]
this is great, thanks a lot! One small thing: in rare cases some annotations are meant to be small like annotations that have a tag, is it possible to disable this feature for tagged annotations? Thanks!

**Comment by berger-n** [comment]
done: https://scamqc.bdrc.io/?folder=demo%2FW1KG8718-I1KG8739%2F
(added a specific color for tagged annotations as well, and display separately in annotation count near image name)

![simplescreenrecorder-2024-02-07_15 54 10 mkv](https://github.com/buda-base/scam/assets/33383857/cc689c8d-c894-40f7-84a8-c40affc1be20)

**Comment by eroux** [comment]
This is perfect, thanks!
