### ISSUE TITLE
Images for W3KG233 not loading in scamqc

### ISSUE THREAD

**Issue by TBRC-Travis** [buda-base/scam#45]
Trying to open this folder:  Travis/contrib/W3KG233/archive/W3KG233-I3KG995

When trying to view images on scamqc they don't appear to load:
https://scamqc.bdrc.io/?folder=Travis%2Fcontrib%2FW3KG233%2Farchive%2FW3KG233-I3KG995%2F

**Comment by berger-n** [comment]
fixed: https://scamqc.bdrc.io/?folder=Travis%2Fcontrib%2FW3KG233%2Farchive%2FW3KG233-I3KG995%2F
(there was an url encoding issue with the '&' character in image path)

![image](https://github.com/buda-base/scam/assets/33383857/351b4a5a-05e0-4a3a-ae86-10b22afb88d0)
