### ISSUE TITLE
Losing changes after saving a draft?

### ISSUE THREAD

**Issue by TBRC-Travis** [buda-base/scam#46]
Well maybe I'm not doing something right here but after saving a draft of annotations (without clicking the upload button) and then I click the 'X" on the current folder (top-right hand corner of screen) to switch to a different work and I get a warning that says "Folder modified: Lose your changes...".

I don't understand why it's telling me I'm going to lose changes when I've just saved a draft.  Am I supposed to click "upload" even when I'm not finished annotating the work?

**Comment by berger-n** [comment]
could be related to https://github.com/buda-base/scam/issues/9
will have a look
