### ISSUE TITLE
add contrast control button

### ISSUE THREAD

**Issue by eroux** [buda-base/scam#47]
In some folders (like `Travis/contrib/W3KG233/archive/W3KG233-I3KG995`) the border between the two images is a little bit difficult to see, especially at lower resolutions (4x3, 3x2, etc.). It could be interesting to have a button to display the images with more contrast (directly from the UI or, if it's really too slow, we could have an option in the server query for the thumbnails

**Comment by berger-n** [comment]
done: https://scamqc.bdrc.io/?folder=Travis%2Fcontrib%2FW3KG233%2Farchive%2FW3KG233-I3KG995%2F

![simplescreenrecorder-2024-02-09_17 04 32 mkv](https://github.com/buda-base/scam/assets/33383857/81625731-703d-4b96-b56c-a6de84c59dee)

**Comment by eroux** [comment]
impressive, thanks a lot!
