### ISSUE TITLE
adding margins to annotation generation

### ISSUE THREAD

**Issue by TBRC-Travis** [buda-base/scam#57]
I'd like to have an option when running SCAM to add a fixed margin to the annotation dimensions that SCAM generates which will increase the dimensions of the annotation box by a fixed amount of pixels.  (Basically the opposite of the "Cut at fixed resolution" option.

For example, when running SCAM against a manuscript like this:
<img width="704" alt="W3CN57_detection" src="https://github.com/buda-base/scam/assets/19354126/85ec4468-76cb-4851-862e-edaac61faf9e">

it detects the edge of where the text is found and I would like to be able to increase the box dimensions by say, 300 pixels on all sides.  Being able to designate a different amount of pixels for the X and Y axis would be ideal.

**Comment by eroux** [comment]
@berger-n I think this would be straightforward to add in the UI right? the parameter is `expand_to_fixed` instead of `cut_at_fixed`

**Comment by berger-n** [comment]
@eroux indeed! looks done: https://scamqc.bdrc.io/?folder=Travis%2FW1ER158%2Farchive%2FW1ER158-I1ER911%2F
not sure how/where to fully test it though?

![image](https://github.com/buda-base/scam/assets/33383857/882cff08-9624-4d0a-bfff-31ea3f42f63b)

**Comment by TBRC-Travis** [comment]
@berger-n I have a volume I can test this on.  will keep you posted.

**Comment by TBRC-Travis** [comment]
I tested this out on `Travis/W3CN57/W3CN57-I3CN287/` but it doesn't appear to do anything.  I tried expanding the annotation to 3200 x 500 and nothing changed.

**Comment by eroux** [comment]
it wasn't implemented on the server side, it seems to be working now

**Comment by eroux** [comment]
closing as fixed
