### ISSUE TITLE
new image filter: outliars

### ISSUE THREAD

**Issue by eroux** [buda-base/scam#58]
In some folders like 

https://scamqc.bdrc.io/?folder=NLM1%2FW8LS31896%2Fsources%2FW8LS31896-I8LS31945%2F

there's an error that's really difficult to detect (especially at QC stage), it's when two pages are erroneously put together. This is much easier to see with the thumbnails off:

![Capture d’écran de 2024-03-03 12-48-26](https://github.com/buda-base/scam/assets/60868/35dc209e-510b-422f-80ee-7f5e661fb4fa)

but still, I think a much more efficient way to spot them would be a new "outliars" image filter.

It would be all images that have at least one non-tagged annotation which width / height factor is off from the rest. To detect those, calculate the medial width / height of non-tagged in the folder and show everything that is above 1.5*median and below 0.75*median. In the case of this folder, those annotations will be around 0.5* median so it should catch them

**Comment by berger-n** [comment]
done: https://scamqc.bdrc.io/?folder=NLM1%2FW8LS31896%2Fsources%2FW8LS31896-I8LS31945%2F

![simplescreenrecorder-2024-03-04_15 21 07 mkv](https://github.com/buda-base/scam/assets/33383857/d1ae20e8-4b45-467b-ae63-47cc3ca0f682)

**Comment by eroux** [comment]
looks great, thanks!
