### ISSUE TITLE
don't display name in mozaic view

### ISSUE THREAD

**Issue by eroux** [buda-base/scam#59]
Sometimes the mozaic view is a bit cluttered with the file names:

![Capture d’écran de 2024-03-03 12-59-10](https://github.com/buda-base/scam/assets/60868/63a9f601-2b97-4494-b9fe-2ee4bcb48715)

since we already can see the name in hover, maybe having it displayed all the time is not very helpful

**Comment by berger-n** [comment]
is it ok like this or do you prefer to remove them completely? 
https://scamqc.bdrc.io/?folder=NLM1%2FW8LS31896%2Fsources%2FW8LS31896-I8LS31945%2F

![image](https://github.com/buda-base/scam/assets/33383857/8e092841-0f2a-4e2c-bd84-bffd6bdf6de1)

**Comment by eroux** [comment]
that's better, thanks!
