### ISSUE TITLE
top menu blinking like crazy

### ISSUE THREAD

**Issue by eroux** [buda-base/scam#6]
it does it on https://scamqc.bdrc.io/?folder=X_Basgo_Complete%2F10+mDo%2FmDo+04+Nga+%28aus+Phal+chen%29%2F 

https://github.com/buda-base/scam/assets/60868/e1b9680b-7ec5-45f2-acb0-2b5fa325c33e

**Comment by berger-n** [comment]
fixed: https://scamqc.bdrc.io/?folder=X_Basgo_Complete%2F10+mDo%2FmDo+04+Nga+%28aus+Phal+chen%29%2F
(might be hard to click the Update button at first though?)

![simplescreenrecorder-2023-10-19_11 29 49 mkv](https://github.com/buda-base/scam/assets/33383857/0e1cfae7-d710-47cd-b1ca-d9b1a48cbae3)
