### ISSUE TITLE
Mark multiple images as hidden

### ISSUE THREAD

**Issue by TBRC-Travis** [buda-base/scam#61]
Is there a way to mark multiple images as hidden?  Right now I tried selecting multiple images but the "mark hidden" option is greyed out.  Wondering if a feature needs to be added or I'm doing something wrong.

**Comment by berger-n** [comment]
should be already working, can you send a screenshot?

**Comment by TBRC-Travis** [comment]
just tried again and seems to be working now.  sorry for the false alarm.
