### ISSUE TITLE
Select a group of images in mozaic view

### ISSUE THREAD

**Issue by TBRC-Travis** [buda-base/scam#62]
It would be great to be able to select a group of images when in moziac view

**Comment by berger-n** [comment]
done: https://scamqc.bdrc.io/?folder=Travis%2FW3CN57%2FW3CN57-I3CN283%2F

![simplescreenrecorder-2024-03-21_18 30 57 mkv](https://github.com/buda-base/scam/assets/33383857/e9dbc3b3-046f-45e9-a2e7-8ee07a6f0a73)
