### ISSUE TITLE
Annotations not loading

### ISSUE THREAD

**Issue by TBRC-Travis** [buda-base/scam#64]
@berger-n I created annotations for W3CN57-I3CN283 that I uploaded but now the annotations don't seem to be loading.  Can you check?

https://scamqc.bdrc.io/?folder=Travis%252FW3CN57%252FW3CN57-I3CN283

**Comment by berger-n** [comment]
if this is the right link https://scamqc.bdrc.io/?folder=Travis%2FW3CN57%2FW3CN57-I3CN283%2F there's nothing regarding saved annotations indeed... @eroux wdyt?

**Comment by eroux** [comment]
https://scamqc.bdrc.io/?folder=Travis%2FW3CN57%2FW3CN57-I3CN283%2F works well (it needs a / at the end)

**Comment by TBRC-Travis** [comment]
@eroux are you seeing the annotations for the `ZJ000XXX-6` images?  They should be annotated (I uploaded the changes last night) but now the annotations aren't showing up for some reason.

**Comment by eroux** [comment]
it seems the json file has not been modified since its creation, see the dates in S3:

![Capture d’écran de 2024-03-25 12-15-53](https://github.com/buda-base/scam/assets/60868/39feff8b-0474-459a-b6c0-8e45576f00af)

I know that it happened to me once that I closed the window, ignore the warning saying it's not saved and then realize I lost my work... I don't think this is a bug scam, but if you ever find a way to reproduce it, please tell us

**Comment by TBRC-Travis** [comment]
The annotations are loading but post-processing isn't working perhaps because there seems be a warning with `ZJ000184-6` that I can't clear.  I manually "checked" the image with a green check mark but it's still showing as a warning.  @berger-n can you take a look?

**Comment by eroux** [comment]
post processing is quite disconnected from the UI, it ignores warnings. what's the error you're getting in the post processing? (this should probably be in a different issue though)

**Comment by TBRC-Travis** [comment]
I just didn't know if warnings were somehow written into the json such that it would prevent post-processing from completing, so it's good to know that it ignores them.  Here are some errors I'm seeing in the post-processing step:
```
_TIFFVSetField: tempfile.tif: Null count for "Tag 32934" (type 4, writecount -3, passcount 1).
_TIFFVSetField: tempfile.tif: Null count for "Tag 32934" (type 4, writecount -3, passcount 1).
```

**Comment by eroux** [comment]
that can be ignored, no problem

**Comment by TBRC-Travis** [comment]
Closing this as annotations are loading fine.

**Comment by berger-n** [comment]
there's a 5th annotation here hence the forced warning (see https://github.com/buda-base/scam/issues/43):

![image](https://github.com/buda-base/scam/assets/33383857/7234b46f-ae6e-4dda-9c18-e7ebd53bb65f)

**Comment by TBRC-Travis** [comment]
ahhhh...I didn't notice that.  thank you!
