### ISSUE TITLE
paste an annotation on multiple pages

### ISSUE THREAD

**Issue by eroux** [buda-base/scam#65]
We have some volumes (a few 100s) where there's virtually no distinction between the pages and we have to just apply a cookie cutter method, splitting the pages in half. For that I think the most generic option would be a "paste in selected images" button (in the image selection menu)

**Comment by berger-n** [comment]
done: http://scamqc.bdrc.io/?folder=Sarah-Library%2FW2KG210280%2Fimages%2FW2KG210280-I3KG366%2F

![simplescreenrecorder-2024-03-22_15 42 07 mkv](https://github.com/buda-base/scam/assets/33383857/ceab1f38-78d9-4676-9049-bdd5a21f8c5c)

**Comment by eroux** [comment]
this is really great, thanks a lot!
