### ISSUE TITLE
paste position algorithm

### ISSUE THREAD

**Issue by eroux** [buda-base/scam#67]
When the dimensions of the image where an annotation is copied are different from those of the image where the annotation is pasted, the following algorithm should be applied:
- find the corner that is the closest to the annotation center in the source image
- paste so that the annotation is at the same position from this corner in the destination image

https://scamqc.bdrc.io/?folder=recrop%2FOther%2FW3CN981%2Farchive%2FW3CN981-I3CN1003%2F for instance is full of images of slightly different sizes, and pasting the bottom annotation is sometimes too low, sometimes too high... that new algorithm will solve the issue

**Comment by berger-n** [comment]
looks done to me: https://scamqc.bdrc.io/?folder=Sarah-Library%2FW2KG210280%2Fimages%2FW2KG210280-I3KG366%2F

![simplescreenrecorder-2024-03-27_11 50 07 mkv](https://github.com/buda-base/scam/assets/33383857/3e105869-8e53-4f51-88b0-a3a3aaf297bd)

**Comment by eroux** [comment]
looks perfect, thanks a lot!!
