### ISSUE TITLE
no effect on unloaded tiles

### ISSUE THREAD

**Issue by eroux** [buda-base/scam#68]
It seems when scam doesn't have a tile in memory, copy/pasting doesn't work. For instance:

[Capture d’écran vidéo de 28-03-2024 17:53:30.webm](https://github.com/buda-base/scam/assets/60868/41d22cee-6d89-499d-a7fa-bdca40b867a1)

(the example is in https://scamqc.bdrc.io/?folder=recrop%2FOther%2FW3CN981%2Farchive%2FW3CN981-I3CN999%2F ). I don't think this is due to mozaic view as it happens in other contexts, but it's just easier to see

**Comment by berger-n** [comment]
not an easy one but finally made it: https://scamqc.bdrc.io/?folder=recrop%2FOther%2FW3CN981%2Farchive%2FW3CN981-I3CN999%2F

![simplescreenrecorder-2024-03-29_17 39 56 mkv](https://github.com/buda-base/scam/assets/33383857/d2726643-7085-4dbf-b927-b22f3f7ee6f1)
