### ISSUE TITLE
"remove annotations in selected images" button

### ISSUE THREAD

**Issue by eroux** [buda-base/scam#69]
Sometimes we need to start again a whole volume from scratch, in that case it's actually not that easy to remove existing annotations. Perhaps a button "remove annotations in selected images" button would be helpful

**Comment by berger-n** [comment]
done: https://scamqc.bdrc.io/?folder=Bruno%2FReruk%2F

![simplescreenrecorder-2024-04-02_12 10 15 mkv](https://github.com/buda-base/scam/assets/33383857/83f658d4-e3e2-4c23-8f6b-268e01d15237)

**Comment by eroux** [comment]
perfect, thanks a lot!
