### ISSUE TITLE
new tags: page number in image

### ISSUE THREAD

**Issue by eroux** [buda-base/scam#70]
Some images look like this:

![Capture d’écran de 2024-03-30 15-14-09](https://github.com/buda-base/scam/assets/60868/c8023327-b51e-417b-a8b8-9e195efa242f)

and unfortunately it's more or less impossible to determine the order of images automatically. In that case we should have tags describing the page number. It could be just `T0101`, `T0102`, etc. in the json, and given this image we should have at list 12. The example is [here](https://scamqc.bdrc.io/?folder=recrop%2FOther%2FW3CN981%2Farchive%2FW3CN981-I3CN1058%2F)

**Comment by berger-n** [comment]
done something like this: https://scamqc.bdrc.io/?folder=recrop%2FOther%2FW3CN981%2Farchive%2FW3CN981-I3CN1058%2F
(could an annotation have multiple page numbers? as of today choosing the number replaces the previous one if any)

![simplescreenrecorder-2024-04-02_16 35 18 mkv](https://github.com/buda-base/scam/assets/33383857/e5a75216-1388-49ff-a393-2986b868737d)

**Comment by eroux** [comment]
that's perfect, thanks a lot!
