### ISSUE TITLE
tools to help review undone files

### ISSUE THREAD

**Issue by eroux** [buda-base/scam#74]
In some cases not all files have had SCAM applied, and some folders are a weird mix of applied and unapplied. Let's make two things to help spot and review those files:

1. in the filters, let's add a new "not done" filter that shows only those files
2. let's add a new "select all filtered images" in the "select" menu
3. let's add a new report next to the total number of warnings: "X files not done"

**Comment by berger-n** [comment]
looks all done: https://scamqc.bdrc.io/?folder=FPL%2FW1EAP10596%2Fsources%2FW1EAP10596-I1EAP10596%2F

![simplescreenrecorder-2024-05-30_18 05 19 mkv](https://github.com/buda-base/scam/assets/33383857/f410bda0-bc8d-4996-be86-7bb5e6ecf1b4)

**Comment by eroux** [comment]
wonderful, thanks a lot!
