### ISSUE TITLE
Selecting multiple images as hidden

### ISSUE THREAD

**Issue by TBRC-Travis** [buda-base/scam#75]
@berger-n I want to be able to hide a selected group of images but the "Mark hidden" option is grayed out

![chrome-capture-2024-6-10](https://github.com/buda-base/scam/assets/19354126/297f0ab0-e1d3-4145-b2bb-02f258fa73e6)

**Comment by berger-n** [comment]
ok! should be fixed now: 
https://scamqc.bdrc.io/?folder=Sarah-Library%2FW2KG210280%2Fimages%2FW2KG210280-I3KG366%2F

![simplescreenrecorder-2024-07-15_15 26 18 mkv](https://github.com/user-attachments/assets/4a619f0a-9c74-4f83-8e37-e6ca47e14100)

**Comment by eroux** [comment]
thanks!
