### ISSUE TITLE
removed annotations come back after upload

### ISSUE THREAD

**Issue by eroux** [buda-base/scam#76]
Steps to reproduce:

- go to https://scamqc.bdrc.io/?folder=NLM1%2FW8LS31885%2Fsources%2FW8LS31885-I8LS32942%2F
- select all
- remove annotations in selected images
- upload
- refresh the page, the annotations are still thee

**Comment by berger-n** [comment]
fixed: https://scamqc.bdrc.io/?folder=Sarah-Library%2FW2KG210280%2Fimages%2FW2KG210280-I3KG366%2F

![simplescreenrecorder-2024-08-12_15 04 45 mkv](https://github.com/user-attachments/assets/e731654a-dfbd-46e9-834c-08b59279cf79)

**Comment by eroux** [comment]
thanks!
