### ISSUE TITLE
ungray save buttons in more circumstances

### ISSUE THREAD

**Issue by eroux** [buda-base/scam#9]
As soon as `run_scam` or `run_scam_file` (on any file) are called, the save buttons should be ungrayed. The use case is that sometimes scam will give a perfect output with no need for intervention, but then the buttons are grayed, with the file still needing to be saved

**Comment by berger-n** [comment]
fixed: https://scamqc.bdrc.io/?folder=Sarah-Library%2FW2KG210280%2Fimages%2FW2KG210280-I3KG366%2F

![simplescreenrecorder-2024-01-04_15 03 18 mkv](https://github.com/buda-base/scam/assets/33383857/651abc1f-d527-4dd7-bb6d-d831772238a1)

**Comment by eroux** [comment]
perfect, thanks!
